version: '2.3'

volumes:
  db_data:

services:
  app:
    build:
      context: .
      target: app
    container_name: authent-app
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
  api:
    build:
      context: .
      target: api
    container_name: authent-api
    command: npm run dev
    ports:
      - "3001:3000"
    volumes:
      - ./api:/app
  db:
    image: postgres:latest
    container_name: authent-db
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - db_data:/var/lib/postgresql/data
