version: '2.3'

services:
  app:
    build:
      context: .
      target: app
    container_name: authent-app
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
  api:
    build:
      context: .
      target: api
    container_name: authent-api
    command: npm run dev
    ports:
      - "3001:3000"
    env_file:
      - api/.env
    volumes:
      - ./api:/app
      - /app/node_modules
